import { readStoredFile } from "@/lib/services/storage";
import { getCurrentUser } from "@/lib/auth";

// Authenticated file serving (docs/10 secure file access): uploads never
// live under public/. Filenames are unguessable random hex generated by us.
export async function GET(_req: Request, { params }: { params: Promise<{ path: string[] }> }) {
  const user = await getCurrentUser();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const { path } = await params;
  if (path.length !== 2) return new Response("Not found", { status: 404 });

  const file = await readStoredFile(path[0], path[1]);
  if (!file) return new Response("Not found", { status: 404 });

  return new Response(new Uint8Array(file.data), {
    headers: {
      "content-type": file.contentType,
      "cache-control": "private, max-age=3600",
      "x-content-type-options": "nosniff",
    },
  });
}
